#!/bin/bash
# bashrc

# #########
# Sourcing
# #########

[[ -f "${XDG_CONFIG_HOME}/bash/alias" ]] && source "${XDG_CONFIG_HOME}/bash/alias"
[[ -f "${XDG_CONFIG_HOME}/bash/function" ]] && source "${XDG_CONFIG_HOME}/bash/function"

# ########
# Prompt
# ########

case "$TERM" in
    xterm-color|*-256color)
        PS1='\[$(suc_last_command)\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
        ;;
    *)
        PS1='\u@\h:\w\$ '
        ;;
esac
