#!/bin/bash
# bash_profile

# ################
# Settings
# ################

# History
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000
PROMPT_COMMAND='history -a ;$PROMPT_COMMAND'
[[ -d "$XDG_STATE_HOME/bash" ]] && HISTFILE="$XDG_STATE_HOME/bash/history"

export HISTCONTROL
export HISTFILE
export HISTSIZE
export HISTFILESIZE
export PROMPT_COMMAND

# Bash
shopt -s checkwinsize
shopt -s globstar
shopt -s dotglob
shopt -s nullglob

# Less
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# #################
# Colors
# #################

# Reset
export CONSOLE_Color_Off="\[\033[0m\]"       # Text Reset

# Regular Colors
export CONSOLE_Black="\[\033[0;30m\]"        # Black
export CONSOLE_Red="\[\033[0;31m\]"          # Red
export CONSOLE_Green="\[\033[0;32m\]"        # Green
export CONSOLE_Yellow="\[\033[0;33m\]"       # Yellow
export CONSOLE_Blue="\[\033[0;34m\]"         # Blue
export CONSOLE_Purple="\[\033[0;35m\]"       # Purple
export CONSOLE_Cyan="\[\033[0;36m\]"         # Cyan
export CONSOLE_White="\[\033[0;37m\]"        # White

# Bold
export CONSOLE_BBlack="\[\033[1;30m\]"       # Black
export CONSOLE_BRed="\[\033[1;31m\]"         # Red
export CONSOLE_BGreen="\[\033[1;32m\]"       # Green
export CONSOLE_BYellow="\[\033[1;33m\]"      # Yellow
export CONSOLE_BBlue="\[\033[1;34m\]"        # Blue
export CONSOLE_BPurple="\[\033[1;35m\]"      # Purple
export CONSOLE_BCyan="\[\033[1;36m\]"        # Cyan
export CONSOLE_BWhite="\[\033[1;37m\]"       # White

# Underline
export CONSOLE_UBlack="\[\033[4;30m\]"       # Black
export CONSOLE_URed="\[\033[4;31m\]"         # Red
export CONSOLE_UGreen="\[\033[4;32m\]"       # Green
export CONSOLE_UYellow="\[\033[4;33m\]"      # Yellow
export CONSOLE_UBlue="\[\033[4;34m\]"        # Blue
export CONSOLE_UPurple="\[\033[4;35m\]"      # Purple
export CONSOLE_UCyan="\[\033[4;36m\]"        # Cyan
export CONSOLE_UWhite="\[\033[4;37m\]"       # White

# Background
export CONSOLE_On_Black="\[\033[40m\]"       # Black
export CONSOLE_On_Red="\[\033[41m\]"         # Red
export CONSOLE_On_Green="\[\033[42m\]"       # Green
export CONSOLE_On_Yellow="\[\033[43m\]"      # Yellow
export CONSOLE_On_Blue="\[\033[44m\]"        # Blue
export CONSOLE_On_Purple="\[\033[45m\]"      # Purple
export CONSOLE_On_Cyan="\[\033[46m\]"        # Cyan
export CONSOLE_On_White="\[\033[47m\]"       # White

# High Intensty
export CONSOLE_IBlack="\[\033[0;90m\]"       # Black
export CONSOLE_IRed="\[\033[0;91m\]"         # Red
export CONSOLE_IGreen="\[\033[0;92m\]"       # Green
export CONSOLE_IYellow="\[\033[0;93m\]"      # Yellow
export CONSOLE_IBlue="\[\033[0;94m\]"        # Blue
export CONSOLE_IPurple="\[\033[0;95m\]"      # Purple
export CONSOLE_ICyan="\[\033[0;96m\]"        # Cyan
export CONSOLE_IWhite="\[\033[0;97m\]"       # White

# Bold High Intensty
export CONSOLE_BIBlack="\[\033[1;90m\]"      # Black
export CONSOLE_BIRed="\[\033[1;91m\]"        # Red
export CONSOLE_BIGreen="\[\033[1;92m\]"      # Green
export CONSOLE_BIYellow="\[\033[1;93m\]"     # Yellow
export CONSOLE_BIBlue="\[\033[1;94m\]"       # Blue
export CONSOLE_BIPurple="\[\033[1;95m\]"     # Purple
export CONSOLE_BICyan="\[\033[1;96m\]"       # Cyan
export CONSOLE_BIWhite="\[\033[1;97m\]"      # White

# High Intensty backgrounds
export CONSOLE_On_IBlack="\[\033[0;100m\]"   # Black
export CONSOLE_On_IRed="\[\033[0;101m\]"     # Red
export CONSOLE_On_IGreen="\[\033[0;102m\]"   # Green
export CONSOLE_On_IYellow="\[\033[0;103m\]"  # Yellow
export CONSOLE_On_IBlue="\[\033[0;104m\]"    # Blue
export CONSOLE_On_IPurple="\[\033[10;95m\]"  # Purple
export CONSOLE_On_ICyan="\[\033[0;106m\]"    # Cyan
export CONSOLE_On_IWhite="\[\033[0;107m\]"   # White

export CONSOLE_CGreen='\033[0;32m'           # Green_without_escape
export CONSOLE_CIRed='\033[0;91m'            # Red_without_escape
export CONSOLE_CColor_Off='\033[0m'          # Text Reset_without_escape

# ##########
# Sourcing
# ##########

[[ -f "${XDG_CONFIG_HOME}/bash/bashrc" ]] && source "${XDG_CONFIG_HOME}/bash/bashrc"



